package main.java;

/**
 * This class provides methods to sort and reverse an array of SalesRepresentative objects.
 * The sorting is done in descending order based on the revenue generated by each sales representative.
 */
public class BubbleSort {

    /**
     * Sorts an array of SalesRepresentative objects in descending order based on revenue generated.
     * Uses the bubble sort algorithm.
     *
     * @param salesRepresentatives the array of SalesRepresentative objects to be sorted
     * @return the sorted array of SalesRepresentative objects
     */
    public SalesRepresentative[] sort(SalesRepresentative[] salesRepresentatives) {
        int arrayLength = salesRepresentatives.length;
        int i, j;
        SalesRepresentative temp;
        boolean swapped;

        for (i = 0; i < arrayLength; i++) {
            swapped = false;
            for (j = 0; j < arrayLength - i - 1; j++) {
                if (salesRepresentatives[j].getRevenueGenerated() < salesRepresentatives[j + 1].getRevenueGenerated()) {
                    temp = salesRepresentatives[j];
                    salesRepresentatives[j] = salesRepresentatives[j + 1];
                    salesRepresentatives[j + 1] = temp;
                    swapped = true;
                }
            }
            if (!swapped) {
                break;
            }
        }
        return salesRepresentatives;
    }

    /**
     * Reverses the order of elements in an array of SalesRepresentative objects.
     *
     * @param salesRepresentatives the array of SalesRepresentative objects to be reversed
     * @return the reversed array of SalesRepresentative objects
     */
    public SalesRepresentative[] reverse(SalesRepresentative[] salesRepresentatives) {
        int arrayLength = salesRepresentatives.length;
        int i;
        SalesRepresentative temp;

        for (i = 0; i < arrayLength / 2; i++) {
            temp = salesRepresentatives[i];
            salesRepresentatives[i] = salesRepresentatives[arrayLength - i - 1];
            salesRepresentatives[arrayLength - i - 1] = temp;
        }
        return salesRepresentatives;
    }
}
